### ISSUE TITLE
SonarQube Administration General Settings Crashed

### ISSUE THREAD

**Issue by iceycake** [gabrie-allaigre/sonar-gitlab-plugin#119]
SonarQube Version: 5.6.1
Gitlab Plugin: 3.0.0

When trying to reach `Administration -> General Settings -> GitLab`, the UI crashed with the following logs:

```
2018.03.15 17:15:59 ERROR web[o.s.s.ui.JRubyFacade] Fail to render: http://sonar.internal.domain/settings?category=gitlab
Missing template settings/_type_LONG.erb in view path app/views:/opt/sonarqube/temp/ror/ldap/app/views
	On line #1 of app/views/settings/_single_value.html.erb

    1: <%= render "settings/type_#{property_type(property, value)}", :property => property, :field => nil, :value => value, :name => input_name(property), :id => "input_#{h property.key}" -%>

    gems/gems/actionpack-2.3.15/lib/action_view/paths.rb:74:in `find_template'
    gems/gems/actionpack-2.3.15/lib/action_view/partials.rb:237:in `_pick_partial_template'
    gems/gems/activesupport-2.3.15/lib/active_support/memoizable.rb:122:in `_pick_partial_template'
    gems/gems/actionpack-2.3.15/lib/action_view/partials.rb:184:in `render_partial'
    gems/gems/actionpack-2.3.15/lib/action_view/base.rb:276:in `render'
    app/views/settings/_single_value.html.erb:1
    org/jruby/RubyKernel.java:2227:in `send'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable.rb:34:in `render'
    gems/gems/actionpack-2.3.15/lib/action_view/base.rb:306:in `with_template'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable.rb:30:in `render'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable_partial.rb:20:in `render'
    gems/gems/actionpack-2.3.15/lib/action_controller/benchmarking.rb:30:in `benchmark'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable_partial.rb:19:in `render'
    gems/gems/actionpack-2.3.15/lib/action_view/template.rb:205:in `render_template'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable_partial.rb:44:in `render_partial'
    gems/gems/actionpack-2.3.15/lib/action_view/partials.rb:184:in `render_partial'
    gems/gems/actionpack-2.3.15/lib/action_view/base.rb:276:in `render'
    app/views/settings/_properties.html.erb:56
    org/jruby/RubyArray.java:1613:in `each'
    app/views/settings/_properties.html.erb:39
    org/jruby/RubyKernel.java:2227:in `send'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable.rb:34:in `render'
    gems/gems/actionpack-2.3.15/lib/action_view/base.rb:306:in `with_template'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable.rb:30:in `render'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable_partial.rb:20:in `render'
    gems/gems/actionpack-2.3.15/lib/action_controller/benchmarking.rb:30:in `benchmark'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable_partial.rb:19:in `render'
    gems/gems/actionpack-2.3.15/lib/action_view/template.rb:205:in `render_template'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable_partial.rb:44:in `render_partial'
    gems/gems/actionpack-2.3.15/lib/action_view/partials.rb:184:in `render_partial'
    gems/gems/actionpack-2.3.15/lib/action_view/base.rb:276:in `render'
    app/views/settings/_settings.html.erb:37
    org/jruby/RubyKernel.java:2227:in `send'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable.rb:34:in `render'
    gems/gems/actionpack-2.3.15/lib/action_view/base.rb:306:in `with_template'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable.rb:30:in `render'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable_partial.rb:20:in `render'
    gems/gems/actionpack-2.3.15/lib/action_controller/benchmarking.rb:30:in `benchmark'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable_partial.rb:19:in `render'
    gems/gems/actionpack-2.3.15/lib/action_view/template.rb:205:in `render_template'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable_partial.rb:44:in `render_partial'
    gems/gems/actionpack-2.3.15/lib/action_view/partials.rb:184:in `render_partial'
    gems/gems/actionpack-2.3.15/lib/action_view/base.rb:276:in `render'
    app/views/settings/index.html.erb:2
    org/jruby/RubyKernel.java:2227:in `send'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable.rb:34:in `render'
    gems/gems/actionpack-2.3.15/lib/action_view/base.rb:306:in `with_template'
    gems/gems/actionpack-2.3.15/lib/action_view/renderable.rb:30:in `render'
    gems/gems/actionpack-2.3.15/lib/action_view/template.rb:205:in `render_template'
    gems/gems/actionpack-2.3.15/lib/action_view/base.rb:265:in `render'
    gems/gems/actionpack-2.3.15/lib/action_view/base.rb:348:in `_render_with_layout'
    gems/gems/actionpack-2.3.15/lib/action_view/base.rb:346:in `_render_with_layout'
    gems/gems/actionpack-2.3.15/lib/action_view/base.rb:262:in `render'
    gems/gems/actionpack-2.3.15/lib/action_controller/base.rb:1252:in `render_for_file'
    gems/gems/actionpack-2.3.15/lib/action_controller/base.rb:936:in `render'
    gems/gems/actionpack-2.3.15/lib/action_controller/benchmarking.rb:51:in `render_with_benchmark'
    gems/gems/actionpack-2.3.15/lib/action_controller/benchmarking.rb:51:in `render_with_benchmark'
    gems/gems/actionpack-2.3.15/lib/action_controller/base.rb:1328:in `default_render'
    gems/gems/actionpack-2.3.15/lib/action_controller/base.rb:1334:in `perform_action'
    gems/gems/actionpack-2.3.15/lib/action_controller/filters.rb:617:in `call_filters'
    gems/gems/actionpack-2.3.15/lib/action_controller/filters.rb:610:in `perform_action_with_filters'
    gems/gems/actionpack-2.3.15/lib/action_controller/benchmarking.rb:68:in `perform_action_with_benchmark'
    gems/gems/actionpack-2.3.15/lib/action_controller/benchmarking.rb:68:in `perform_action_with_benchmark'
    gems/gems/actionpack-2.3.15/lib/action_controller/rescue.rb:160:in `perform_action_with_rescue'
    gems/gems/actionpack-2.3.15/lib/action_controller/flash.rb:151:in `perform_action_with_flash'
    org/jruby/RubyKernel.java:2223:in `send'
    gems/gems/actionpack-2.3.15/lib/action_controller/base.rb:532:in `process'
    gems/gems/actionpack-2.3.15/lib/action_controller/filters.rb:606:in `process_with_filters'
    gems/gems/actionpack-2.3.15/lib/action_controller/base.rb:391:in `process'
    gems/gems/actionpack-2.3.15/lib/action_controller/base.rb:386:in `call'
    gems/gems/actionpack-2.3.15/lib/action_controller/routing/route_set.rb:450:in `call'
    gems/gems/actionpack-2.3.15/lib/action_controller/dispatcher.rb:87:in `dispatch'
    gems/gems/actionpack-2.3.15/lib/action_controller/dispatcher.rb:85:in `dispatch'
    gems/gems/actionpack-2.3.15/lib/action_controller/dispatcher.rb:121:in `_call'
    gems/gems/actionpack-2.3.15/lib/action_controller/dispatcher.rb:130:in `build_middleware_stack'
    org/jruby/RubyProc.java:290:in `call'
    org/jruby/RubyProc.java:224:in `call'
    gems/gems/activerecord-2.3.15/lib/active_record/query_cache.rb:29:in `call'
    gems/gems/activerecord-2.3.15/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
    gems/gems/activerecord-2.3.15/lib/active_record/query_cache.rb:9:in `cache'
    gems/gems/activerecord-2.3.15/lib/active_record/query_cache.rb:28:in `call'
    gems/gems/activerecord-2.3.15/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
    config/environment.rb:67:in `call'
    gems/gems/actionpack-2.3.15/lib/action_controller/string_coercion.rb:25:in `call'
    gems/gems/actionpack-2.3.15/lib/action_controller/params_parser.rb:15:in `call'
    file:/opt/sonarqube/lib/server/jruby-rack-1.1.13.2.jar!/jruby/rack/session_store.rb:70:in `context'
    gems/gems/actionpack-2.3.15/lib/action_controller/failsafe.rb:26:in `call'
    gems/gems/actionpack-2.3.15/lib/action_controller/dispatcher.rb:106:in `call'
    file:/opt/sonarqube/lib/server/jruby-rack-1.1.13.2.jar!/rack/adapter/rails.rb:34:in `serve_rails'
    file:/opt/sonarqube/lib/server/jruby-rack-1.1.13.2.jar!/rack/adapter/rails.rb:39:in `call'
    file:/opt/sonarqube/lib/server/jruby-rack-1.1.13.2.jar!/rack/handler/servlet.rb:22:in `call'
```

**Comment by gabrie-allaigre** [comment]
Hi, sorry for bug.
I don't know.
Log says `app/views:/opt/sonarqube/temp/ror/ldap/app/views` ldap ??

**Comment by iceycake** [comment]
Looks like plugin 2.1.0 works but not 3.0.0.  What's the compatibility matrix on version 3.0.x plugin?

**Comment by sewolf** [comment]
For posterity, the property "sonar.gitlab.query_wait" don't work with PropertyType.LONG. With PropertyType.INTEGER there are no problems.
