### ISSUE TITLE
Unable to comment the commit

### ISSUE THREAD

**Issue by cadrogui** [gabrie-allaigre/sonar-gitlab-plugin#148]
Hi, im trying to integrate the plugin but when I ran sonar I have this issue:

`
sonar-scanner -Dsonar.host.url=http://code.underflow.cl -Dsonar.login=SONAR_TOKEN -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=6ade8924edf7d5ce8f21a96c35f6782dd1b55725 -Dsonar.gitlab.ref_name=ci -Dsonar.gitlab.project_id=ID_PROJECT -Dsonar.gitlab.failure_notification_mode=exit-code -Dsonar.gitlab.url=GITLAB_URL -Dsonar.gitlab.user_token=GITLAB_USER_TOKEN -Dsonar.sourceEncoding=UTF-8 -Dsonar.gitlab.api_version=v4 -X
`

and then I have this debug.

`````
14:01:39.803 INFO: ANALYSIS SUCCESSFUL
14:01:39.805 DEBUG: Post-jobs : GitLab Commit Issue Publisher (wrapped)
14:01:39.806 INFO: Executing post-job GitLab Commit Issue Publisher (wrapped)
14:01:39.816 DEBUG: getRevisionForLine app/providers/menu.js Line{number=40, content='      rol == undefined ? [] : rol = _rol'}
14:01:39.816 DEBUG: getRevisionForLine {.gitlab-ci.yml=[Line{number=6, content='    - sonar-scanner -Dsonar.sources=app -Dsonar.host.url=$CI_SONAR_URL -Dsonar.login=$CI_SONAR_LOGIN -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_REF -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.failure_notification_mode=exit-code'}, Line{number=-1, content='++ b/.gitlab-ci.yml'}], app/controller/app_controller.js=[Line{number=37, content='      })'}, Line{number=36, content='          controller: 'WelcomeController as vm''}, Line{number=-1, content='++ b/app/controller/app_controller.js'}, Line{number=34, content='      $modal.open({'}, Line{number=35, content='          templateUrl: 'app/views/welcome.html','}]}
14:01:39.817 DEBUG: getRevisionForLine notfound
14:01:39.817 DEBUG: Revision for issue org.sonar.scanner.postjob.DefaultPostJobContext$DefaultIssueWrapper@38f617f4 null false
14:01:39.817 DEBUG: inputComponent app/providers/menu.js 40
14:01:39.819 DEBUG: getRevisionForLine app/controller/login_controller.js Line{number=58, content='        let obj = obj'}
14:01:39.819 DEBUG: getRevisionForLine {.gitlab-ci.yml=[Line{number=6, content='    - sonar-scanner -Dsonar.sources=app -Dsonar.host.url=$CI_SONAR_URL -Dsonar.login=$CI_SONAR_LOGIN -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_REF -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.failure_notification_mode=exit-code'}, Line{number=-1, content='++ b/.gitlab-ci.yml'}], app/controller/app_controller.js=[Line{number=37, content='      })'}, Line{number=36, content='          controller: 'WelcomeController as vm''}, Line{number=-1, content='++ b/app/controller/app_controller.js'}, Line{number=34, content='      $modal.open({'}, Line{number=35, content='          templateUrl: 'app/views/welcome.html','}]}
14:01:39.819 DEBUG: getRevisionForLine notfound
14:01:39.819 DEBUG: Revision for issue org.sonar.scanner.postjob.DefaultPostJobContext$DefaultIssueWrapper@7fc7152e null false
14:01:39.819 DEBUG: inputComponent app/controller/login_controller.js 58
14:01:39.820 DEBUG: getRevisionForLine app/controller/login_controller.js Line{number=57, content='      function toBugIncode(obj){'}
14:01:39.820 DEBUG: getRevisionForLine {.gitlab-ci.yml=[Line{number=6, content='    - sonar-scanner -Dsonar.sources=app -Dsonar.host.url=$CI_SONAR_URL -Dsonar.login=$CI_SONAR_LOGIN -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_REF -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.failure_notification_mode=exit-code'}, Line{number=-1, content='++ b/.gitlab-ci.yml'}], app/controller/app_controller.js=[Line{number=37, content='      })'}, Line{number=36, content='          controller: 'WelcomeController as vm''}, Line{number=-1, content='++ b/app/controller/app_controller.js'}, Line{number=34, content='      $modal.open({'}, Line{number=35, content='          templateUrl: 'app/views/welcome.html','}]}
14:01:39.820 DEBUG: getRevisionForLine notfound
14:01:39.820 DEBUG: Revision for issue org.sonar.scanner.postjob.DefaultPostJobContext$DefaultIssueWrapper@13d289c7 null false
14:01:39.820 DEBUG: inputComponent app/controller/login_controller.js 57
14:01:40.778 ERROR: SonarQube failed to complete the review of this commit
java.lang.IllegalStateException: Unable to comment the commit
	at com.talanlabs.sonar.plugins.gitlab.GitLabApiV4Wrapper.addGlobalComment(GitLabApiV4Wrapper.java:280)
	at com.talanlabs.sonar.plugins.gitlab.CommitFacade.addGlobalComment(CommitFacade.java:136)
	at com.talanlabs.sonar.plugins.gitlab.CommitIssuePostJob.updateGlobalComments(CommitIssuePostJob.java:190)
	at com.talanlabs.sonar.plugins.gitlab.CommitIssuePostJob.execute(CommitIssuePostJob.java:75)
	at org.sonar.scanner.postjob.PostJobWrapper.executeOn(PostJobWrapper.java:58)
	at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:66)
	at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:94)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:302)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:297)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:271)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: com.talanlabs.gitlab.api.v4.GitLabAPIException: {"message":"500 Internal Server Error"}
	at com.talanlabs.gitlab.api.v4.http.GitLabHTTPRequestor.handleAPIError(GitLabHTTPRequestor.java:378)
	at com.talanlabs.gitlab.api.v4.http.GitLabHTTPRequestor.to(GitLabHTTPRequestor.java:125)
	at com.talanlabs.gitlab.api.v4.http.GitLabHTTPRequestor.to(GitLabHTTPRequestor.java:95)
	at com.talanlabs.gitlab.api.v4.services.GitLabAPICommits.postCommitComments(GitLabAPICommits.java:135)
	at com.talanlabs.sonar.plugins.gitlab.GitLabApiV4Wrapper.addGlobalComment(GitLabApiV4Wrapper.java:278)
	... 34 common frames omitted
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://git.underflow.cl/api/v4/projects/55/repository/commits/6ade8924edf7d5ce8f21a96c35f6782dd1b55725/comments
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at com.talanlabs.gitlab.api.v4.http.GitLabHTTPRequestor.parse(GitLabHTTPRequestor.java:336)
	at com.talanlabs.gitlab.api.v4.http.GitLabHTTPRequestor.to(GitLabHTTPRequestor.java:123)
	... 37 common frames omitted

14:01:40.786 INFO: Task total time: 10.375 s
14:01:40.884 INFO: ------------------------------------------------------------------------
14:01:40.884 INFO: EXECUTION SUCCESS
14:01:40.884 INFO: ------------------------------------------------------------------------
14:01:40.884 INFO: Total time: 14.067s
14:01:40.975 INFO: Final Memory: 19M/343M
14:01:40.975 INFO: ------------------------------------------------------------------------
`````

what can I do?

regards.

**Comment by ricardona** [comment]
You are using `-Dsonar.gitlab.commit_sha=$CI_COMMIT_REF` instead of 
`-Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA`
