### ISSUE TITLE
New GitLab API not working -> GitLab 9.4.x

### ISSUE THREAD

**Issue by TheHenrik** [gabrie-allaigre/sonar-gitlab-plugin#55]
After upgrade to the latest release (9.4) of GitLab the sonar-gitlab-plugin ist not working anymore. I'm using the version `2.1.0-beta1` of sonar-gitlab-plugin. 

`[ERROR] SonarQube failed to complete the review of this commit
java.lang.IllegalStateException: Unable to create retrive author for commit 6125a4402073ba412edd27f7a8b4001ad1de8e75
	at com.talanlabs.sonar.plugins.gitlab.GitLabApiV3Wrapper.getUsernameForRevision(GitLabApiV3Wrapper.java:192)
	at com.talanlabs.sonar.plugins.gitlab.CommitFacade.getUsernameForRevision(CommitFacade.java:99)
	at com.talanlabs.sonar.plugins.gitlab.CommitIssuePostJob.updateGlobalComments(CommitIssuePostJob.java:187)
	at com.talanlabs.sonar.plugins.gitlab.CommitIssuePostJob.execute(CommitIssuePostJob.java:75)
	at org.sonar.scanner.postjob.PostJobWrapper.executeOn(PostJobWrapper.java:58)
	at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65)
	at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:54)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:81)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:178)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:259)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:254)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:243)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy42.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:77)
	at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:139)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.talanlabs.gitlab.api.v3.GitLabAPIException: {"message":"403 Forbidden  - Not authorized to access /api/v4/users"}
	at com.talanlabs.gitlab.api.v3.http.GitLabHTTPRequestor.handleAPIError(GitLabHTTPRequestor.java:378)
	at com.talanlabs.gitlab.api.v3.http.GitLabHTTPRequestor.toPaged(GitLabHTTPRequestor.java:149)
	at com.talanlabs.gitlab.api.v3.services.GitLabAPIUsers.getUsers(GitLabAPIUsers.java:59)
	at com.talanlabs.sonar.plugins.gitlab.GitLabApiV3Wrapper.getUsernameForRevision(GitLabApiV3Wrapper.java:178)
	... 54 common frames omitted
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://gitlab/api/v3/users?search=%40xxxxxx
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at com.talanlabs.gitlab.api.v3.http.GitLabHTTPRequestor.parse(GitLabHTTPRequestor.java:336)
	at com.talanlabs.gitlab.api.v3.http.GitLabHTTPRequestor.toPaged(GitLabHTTPRequestor.java:144)
	... 56 common frames omitted`

**Comment by e-j** [comment]
Just ran into same issue. 
After some research it appear that it's linked to new permissions management in Gitlab api v4, users list cannot be obtain that easily as before...
https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/12445

As workaround, you need to go into your gitlab application settings and change **Restricted visibility levels** for uncheck **Public** then save parameters
But I guess this is not very good on security of the global instance

**Comment by TheHenrik** [comment]
Ah, thanks @e-j ! With this workaround it's working.

**Comment by alexander-frolov** [comment]
They fixed this in two stages. First, they fixed this just for the admin users (https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/13066) but then people complained that general authenticated users need access to this API as well (https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/13201). For instance, we do not use admin user to enable integration between SonarQube and GitLab. The second fix was merged to the GitLab CE master branch just today and we need to wait for the availability in GitLab EE.

I think sonar-gitlab-plugin has nothing to do with this issue. We just need to wait for the availability of the fix.

**Comment by TheHenrik** [comment]
Okay, its now working for me with the latest GitLab (9.4.3) release!
