### ISSUE TITLE
Unable to perform GitLab WS operation timeout

### ISSUE THREAD

**Issue by KevinSilvaQuintana** [gabrie-allaigre/sonar-gitlab-plugin#56]
I am trying to set up our Java projects with the plugin. 

I have successfully created the project in sonar by running the following command to execute a full analysis:

    # For performing full analysis on all the code
    sonarqube:
      script:
        - mvn -DskipTests=true --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL
      stage: test
      only:
        - develop

However, when trying to run the analysis on preview mode to enable the plugin, I get a very uninformative Timeout exception. 

    [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar (default-cli) on project sirius-udfs: Unable to load component class org.sonar.scanner.scan.ImmutableProjectReactor: Failed to execute project builder: com.talanlabs.sonar.plugins.gitlab.CommitProjectBuilder: Unable to perform GitLab WS operation: Connection timed out (Connection timed out) -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar (default-cli) on project sirius-udfs: Unable to load component class org.sonar.scanner.scan.ImmutableProjectReactor
    (... more logs)
    Caused by: Failed to execute project builder: com.talanlabs.sonar.plugins.gitlab.CommitProjectBuilder
    Caused by: java.lang.IllegalStateException: Unable to perform GitLab WS operation
    (... more logs)
    Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	  at java.net.PlainSocketImpl.socketConnect(Native Method)
	  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	  at java.net.Socket.connect(Socket.java:589)
	  at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	  at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	  at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	  at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	  at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	  at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	  at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	  at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	  at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	  at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	  at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	  at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	  at com.talanlabs.gitlab.api.http.GitLabHTTPRequestor.parse(GitLabHTTPRequestor.java:336)
	  at com.talanlabs.gitlab.api.http.GitLabHTTPRequestor.toPaged(GitLabHTTPRequestor.java:144)
	... 78 more

As far as I know, I am setting the correct settings:

    sonarqube-preview:
      stage: test
      script:
        - git config --global user.email $GITLAB_USER_EMAIL
        - git checkout origin/develop
        - git merge $CI_COMMIT_SHA --no-commit --no-ff
        - mvn --batch-mode verify sonar:sonar -e -DskipTests=true -Dsonar.analysis.mode=preview -Dsonar.host.url=$SONAR_URL -Dsonar.gitlab.user_token=$SONAR_USER_TOKEN -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.log.level=DEBUG -Dsonar.issuesReport.console.enable=true -DcommentNoIssue=true
   
      except:
        - develop
        - master
        - /^hotfix_.*$/
        - /.*-hotfix$/

I have verified that my `sonar.gitlab.user_token` and `Dsonar.gitlab.commit_sh` is being correctly set from Sonar admin settings. 

I am forcing sonar-maven-plugin version 3.2 in my pom.xml to avoid having the timeout exception when using 3.3.0.603: 
`java.lang.IllegalStateException: Fail to get bootstrap index from server`. But not I'm stuck just a little further.

    <pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.sonarsource.scanner.maven</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
                <version>3.2</version>
            </plugin>
        </plugins>
    </pluginManagement>

Our sonar instance is not set with SSL as far as I'm concerned because so there is no need to specify `-Dsonar.user` or `-Dsonar.password` to run an analysis without the plugin. 

Extra information:
- The scanner works when configured by another team using the MsBuild scanner. @jairbubbles
- We are using version 2.1.0-beta1
-  Je parle francais egalement si tu te sens plus a l'aise la dedans.

**Comment by gabrie-allaigre** [comment]
Bonjour,

Est ce que le runner accède bien au server de sonarqube ?

**Comment by JoshuaRogers** [comment]
I ran into this exact issue last evening. I found that this occurred if I tried to perform analysis on a branch before that branch had been pushed into GitLab. Once a branch was pushed into GitLab, I could not make this issue occur.
