### ISSUE TITLE
While running sonar preview - Unable to perform GitLab WS operation (301 Moved Permanently)

### ISSUE THREAD

**Issue by Lexxxxik** [gabrie-allaigre/sonar-gitlab-plugin#71]
Hello
Some days ago I have faced with the following problem.
I have gitlab-runner witch starts ant task for sonar preview.  But now I see the next error:

```
Failed to execute project builder: com.talanlabs.sonar.plugins.gitlab.CommitProjectBuilder
Caused by: java.lang.IllegalStateException: Unable to perform GitLab WS operation
..............
Caused by: com.talanlabs.gitlab.api.v3.GitLabAPIException
	at com.talanlabs.gitlab.api.v3.http.GitLabHTTPRequestor.handleAPIError(GitLabHTTPRequestor.java:378)
	at com.talanlabs.gitlab.api.v3.http.GitLabHTTPRequestor.toPaged(GitLabHTTPRequestor.java:149)
	at com.talanlabs.gitlab.api.v3.services.GitLabAPIProjects.getProjects(GitLabAPIProjects.java:101)
	at com.talanlabs.gitlab.api.v3.services.GitLabAPIProjects.getProjects(GitLabAPIProjects.java:43)
	at com.talanlabs.sonar.plugins.gitlab.GitLabApiV3Wrapper.getGitLabProject(GitLabApiV3Wrapper.java:90)
	at com.talanlabs.sonar.plugins.gitlab.GitLabApiV3Wrapper.init(GitLabApiV3Wrapper.java:63)
	... 71 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1461)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3602)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3547)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at com.talanlabs.gitlab.api.v3.http.GitLabHTTPRequestor.parse(GitLabHTTPRequestor.java:339)
	at com.talanlabs.gitlab.api.v3.http.GitLabHTTPRequestor.toPaged(GitLabHTTPRequestor.java:144)
```
Full log:
[gitlab-sonar.log.txt](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/files/1344450/gitlab-sonar.log.txt)
[gitlab-sonar-wide.log.txt](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/files/1344468/gitlab-sonar-wide.log.txt)

I understand that my sonar server response wrong by some reasons. 
But when I turn on verbose I see that others requests/responses are ok
I have latest one SonarQube 6.5.
I tied to completely reinstall it, but result the same.
Perhaps you have any ideas how to analyze and resolve this issue?

**Comment by gabrie-allaigre** [comment]
Hi,
What is gitlab's version ?

**Comment by Lexxxxik** [comment]
It is: **GitLab Community Edition 10.0.2 06a5a33**
But it seems to that it worked some days ago when this version was released

**Comment by gabrie-allaigre** [comment]
In your log : `301 Moved Permanently`, you moved gitlab?

**Comment by Lexxxxik** [comment]
I saw this error but thought about SonarServer, not about GitLab
Thanks a lot. We tested some settings HTTP/HTTPS for gitlab, and "GitLab url" prop in Sonar wasn't changed back.
Now I fixed it back to HTTPS and it works as expected.
